### ISSUE TITLE
Output cookie jar with "[Circular]"

### ISSUE THREAD

**Issue by Rympau** [coolaj86/jarson#2]
I'm using mikeal's request library and I need to store in user session variable some cookie jar for requests . Directly passing cookie jar to session variable and retrieve it doesn't work, so I created nasty manual solution and it works. Today I found your library, which is much better than my way.

Unfortunatelly retrieved cookie jar has different construction with "[Circular]".

Example below. tmpCookieJar is jar which I want to pass.

console.log(tmpCookieJar) produces:
{ _jar: { store: { idx: { 'dev.mydomain.net': { '/api': { session: Cookie="session=1417811628137681_otIyMWSdBMPcKn; Path=/api; Version=1; hostOnly=true; aAge=2ms; cAge=2ms" } } } } } }

Then I store it this way:
req.session.userWebApiCookieJar = JSON.stringify(JarSON.toJSON(tmpCookieJar));  

In other call I retrieve it this way:
var userWebApiCookieJar = JarSON.fromJSON(JSON.parse(req.session.userWebApiCookieJar));

and console.log(userWebApiCookieJar) produces:
{ store: { idx: { 'dev.mydomain.net': { '/api': { session: Cookie="session=1417811628137681_otIyMWSdBMPcKn; Path=/api; Version=1; hostOnly=true; aAge=13963ms; cAge=13963ms" } } } },
  _jar: [Circular] }

... which is useless because produces TypeError: Cannot read property 'secure' of undefined when I try to use this cookie jar.

Is it some issue or I'm doing something wrong?

**Comment by coolaj86** [comment]
This is the full error:

```
Unhandled rejection TypeError: Cannot read property 'secure' of undefined
    at CookieJar.getCookies (/srv/node_modules/jarson/node_modules/tough-cookie/lib/cookie.js:946:23)
    at CookieJar.getCookieString (/srv/node_modules/jarson/node_modules/tough-cookie/lib/cookie.js:1044:19)
    at Request.jar (/srv/node_modules/request/request.js:1584:33)
    at Request.init (/srv/node_modules/request/request.js:440:8)
    at new Request (/srv/node_modules/request/request.js:264:8)
    at request (/srv/node_modules/request/index.js:50:10)
```

And it it caused by not having version `2.44.0`.

I just ran into this today because I had the correct version in my `package.json`, but I had done an `npm update` or `npm install request@latest` which broke all the things.

One day when I'm rich and have lots of time I'll figure out how the new cookie parsing and whatnot works.
